### ISSUE TITLE
Site tagline hidden

### ISSUE THREAD

**Issue by aoduor** [ushahidi/uchaguzi#10]
My site name is "Uchaguzi 2013" and tagline is "Uchaguzi 2013 rocks"
The tagline is hidden somewhere on the header. See

![screenshot](http://i.imgur.com/PYjti.png)

It should be as visible as the Site name

**Comment by kamaulynder** [comment]
Fixed
![Screen Shot 2013-01-16 at 12 36 05 PM](https://f.cloud.github.com/assets/155218/70756/4d999070-5fc0-11e2-91ef-6e4af329e9c9.png)
