### ISSUE TITLE
Skewed UI on Admin Reports listing page after adding Search functionality

### ISSUE THREAD

**Issue by aoduor** [ushahidi/uchaguzi#113]
See ![screenshot](http://i.imgur.com/5yXRbnK.png)

**Comment by aoduor** [comment]
Related to #110

**Comment by rjmackay** [comment]
Just tested this and it seems like a weird CSS caching issue.
I loaded and hard refreshed http://uchaguzi.ushahididev.com/media/css/admin/all.css and then this looks fine.
Merge of #110 seems to have gone OK.

**Comment by kamaulynder** [comment]
This is fixed.
