### ISSUE TITLE
Reports Access Level - cannot edit report

### ISSUE THREAD

**Issue by srutto** [ushahidi/uchaguzi#122]
With the reports access level, the user cannot edit a single report. When you click on a single report the view reports page just reloads. The user should be able to edit the reports in the system.

**Comment by rrbaker** [comment]
Reconfirming that this is the case and not limited to just the reports access level.  I've run into this issue from the translator and geolocation roles as well.  Clicking on the report from the reports list returns the user to the reports page.

**Comment by rjmackay** [comment]
A quick digg and it looks like this is a bug in the election plugin

plugins/election/hook/election.php line 473 https://github.com/ushahidi/uchaguzi/blob/master/plugins/election/hooks/election.php#L473
this code is checking for superadmin/admin role.
I'm not sure what the logic there is actually supposed to do though so can't fix it mysql easily

**Comment by kamaulynder** [comment]
Fixed for now
