### ISSUE TITLE
Category Checkboxes disappearing

### ISSUE THREAD

**Issue by srutto** [ushahidi/uchaguzi#123]
Go to Tools/Create Report
Click on Translation Category
Check "Translated"

The check-boxes appear and disappear as you hover the mouse pointer over them. This behaviour is only seen with Firefox browser. On Chrome and Safari it doesn't happen.

![Screen_Shot_2013-03-01_at_9 48 25_AM](https://f.cloud.github.com/assets/1751822/211636/132d0fb0-82bc-11e2-9c02-c9b937e0db75.png)

![Screen_Shot_2013-03-01_at_9 48 52_AM](https://f.cloud.github.com/assets/1751822/211638/24c41e08-82bc-11e2-89e0-87944882bf8c.png)

**Comment by kamaulynder** [comment]
Closing this, looks ok.

**Comment by heatherleson** [comment]
This bug is back  

example 
1. click on it http://cl.ly/image/331m1h3d0B2E

https://uchaguzi.co.ke/admin/reports/edit/418
1. disappears: http://cl.ly/image/3L0A151b0T2e

Experience: 
click on 'urgent' 
can't deselect
can't remove 'urgent' then the box disappears.
