### ISSUE TITLE
SMS Thread Indicator in Summary Page

### ISSUE THREAD

**Issue by om-design** [ushahidi/uchaguzi#128]
when messages are sent from the system, the reply is indicated on the report page by using the "show messages" link (upper right side)

It would help the workflow and reduce system traffic, if the summary sheet https://uchaguzi.co.ke/admin/messages could show the little blue plus-sign icon, if that message has any ongoing correspondence.

I would use the same "Show Messages" functionality. If present, that link would indicate that a reply had gone outbound and any subsequent replies.

In this way, SMS team can quickly see if that message is to be left alone. Coleads can also see the status of a report (responded to or not etc.) quickly without requiring a pageload just to see that it was not necessary to do anything.

**Comment by rjmackay** [comment]
Possibly related to #147

**Comment by rjmackay** [comment]
![Screen Shot 2013-03-04 at 6 03 40 PM](https://f.cloud.github.com/assets/7965/215437/611104a0-848a-11e2-9ab8-0c8f914574bf.png)

**Comment by rjmackay** [comment]
Fixed by     5b84240
