### ISSUE TITLE
On Reports Page, Show Messages Option Fails at Random

### ISSUE THREAD

**Issue by ghost** [ushahidi/uchaguzi#130]
On Reports Page, the 'show message' option fails to drop down, including when page is refreshed, and sometimes will showmessage briefly, and then disappears.

**Comment by rjmackay** [comment]
I think this is now fixed. Reopen if needed

**Comment by ghost** [comment]
Thanks @rjmackay sorry didn't respond sooner didn't see this until now, it's fixed, ty much!
