### ISSUE TITLE
Disable auto-upgrader

### ISSUE THREAD

**Issue by brianherbert** [ushahidi/uchaguzi#132]
Uchaguzi cannot be upgraded via the auto-upgrader so it should be disabled. There's a setting in the config, "enable_auto_upgrader" that should be set to FALSE.

http://cl.ly/image/2c47030i2A3L
<img src="http://f.cl.ly/items/001L162p3a330U440U2p/Screen%20Shot%202013-03-03%20at%2012.08.33%20PM.png" />

**Comment by rjmackay** [comment]
I've disabled this in config on live.

On Sun, Mar 3, 2013 at 4:11 PM, Brian Herbert notifications@github.comwrote:

> Uchaguzi cannot be upgraded via the auto-upgrader so it should be
> disabled. There's a setting in the config, "enable_auto_upgrader" that
> should be set to FALSE.
> 
> http://cl.ly/image/2c47030i2A3L
> 
> https://a248.e.akamai.net/camo.github.com/23c33b67e664ed8dcf876bcce1605aa99c94235b/687474703a2f2f662e636c2e6c792f6974656d732f3030314c313632703361333330553434305532702f53637265656e25323053686f74253230323031332d30332d3033253230617425323031322e30382e3333253230504d2e706e67
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ushahidi/uchaguzi/issues/132
> .

## 

Robbie Mackay

Software Developer, External Projects
Ushahidi Inc
m: +64 27 576 2243
e: robbie@ushahidi.com
skype: robbie.mackay
