### ISSUE TITLE
Possible loss to Unique ID consistency

### ISSUE THREAD

**Issue by kkoxenberners** [ushahidi/uchaguzi#134]
Noticed that when looking at a report from the https://uchaguzi.co.ke/admin/messages page, say of Message #1765, that it comes up with a report - 
https://uchaguzi.co.ke/admin/reports/edit/285
 which has a different number - #285.

Spoke to Heather and she didn't expect to find this - thought once a message got a number it would stick with it throughout the system.

Thanks

Brendan

**Comment by rjmackay** [comment]
Message # and reports # are different references. Since 1 report may relate to multiple messages.
This is the expected behaviour
