### ISSUE TITLE
Make Location field non-required for logged in users (all roles)

### ISSUE THREAD

**Issue by rrbaker** [ushahidi/uchaguzi#136]
The Reports team is requesting that the required Location field be non-required for workflow issues.

As it stands now, in order to save all reports categorized as "To be Geolocated", the Location field requires some content (as is the standard functionality).  They are either putting in "Kenya" or some junk data so they are able to save the report.  This is leading to this field being overlooked, ignored, or confusing to the volunteers on the Geolocation team.  Making this non-required means they can hand the whole report over the to Geolocation team.

**Comment by rrbaker** [comment]
Reopening -- the functionality needs to be that volunteers are able to save the location field without any value (i.e., it is non-required).

**Comment by rjmackay** [comment]
need a little clarification 

the requirement for location (lat,lon) is solidly hardwired in.. hence David's previous solution.

Am I right that the key issue here is the "location name" requirement?
Can I leave a marker on the map (and lat, lon in the db).. but only require location name when approving a report? would that make sense?
