### ISSUE TITLE
Edit categories

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/uchaguzi#16]
Unable to edit categories.

Attempted to change "hate speech" to "dangerous speech" 
1. http://simulation.uchaguzi.co.ke/admin/dashboard
2. Click Manage
3. Click edit "hate Speech" http://cl.ly/image/2t1C1P2n1j1I
4. Unable to edit http://cl.ly/image/0Y2I3h471r0k 

Also note: The Manage toolbar is missing so navigating is difficult

**Comment by kamaulynder** [comment]
This is fixed.
