### ISSUE TITLE
RSS Feed thumbnails

### ISSUE THREAD

**Issue by dkobia** [ushahidi/uchaguzi#17]
The UI calls for News Feeds with thumbnails (if available). I'm not entirely sure we can achieve this in a timely way at the moment @kamaulynder @Jepchumba - I'm still looking into it? Also how would we address rss feeds that don't have an attached image? With a replacement image or blank?

**Comment by dkobia** [comment]
@eyedol would you be willing to look into this? Talk to @Jepchumba about the specific thumbnail size.

**Comment by eyedol** [comment]
A replacement sounds like an ideal solution.

@dkobia  I'll take a look at it.

**Comment by kamaulynder** [comment]
Closing this as we are currently not displaying feeds with the current UI
