### ISSUE TITLE
Action tab for Ushahidi not working?

### ISSUE THREAD

**Issue by matpng** [ushahidi/uchaguzi#174]
Hi I have an issue..I cannot access my ushahidi action settings...it gives me error message below..please help?

"
Parse error: syntax error, unexpected T_FUNCTION in /hermes/bosoraweb122/b1235/ipg.matrixpngcom/public_html/smsiss/application/views/admin/manage/actions/main.php on line 297
"

**Comment by rjmackay** [comment]
This is not an issue for Uchaguzi - but for Ushahidi in general. Closing

**Comment by matpng** [comment]
rjmackay..you are right.posted in the wrong section..but need a fix please?

**Comment by aoduor** [comment]
Hi @matpng, please log this issue at https://github.com/ushahidi/Ushahidi_Web/issues and we'll look into it.

Thanks!
