### ISSUE TITLE
Filter Report Box on reports listing page not working

### ISSUE THREAD

**Issue by aoduor** [ushahidi/uchaguzi#18]
Steps to reproduce:-
1. Go to reports listing page on frontend
2. Click on any category checkbox

Expected result
- Category checkbox should be clickable, and reports filtered should belong to that category only

Actual result
- Category checkbox is not clickable/is non responsive. Actually the entire filter by category section is non responsive. Errors thrown can be seen below

![screenshot](http://i.imgur.com/0E0rE7x.png)

**Comment by kamaulynder** [comment]
Fixed
