### ISSUE TITLE
County Select on Main Page is Too Long

### ISSUE THREAD

**Issue by dkobia** [ushahidi/uchaguzi#22]
On the right hand column on the front page, we need to use something like a CSS overflow so that when counties are opened, one can scroll up and down within a fixed space. It's also a slight annoyance when you can't see the county you've selected and have to scroll the page up to see it.

**Comment by brandonrosage** [comment]
Done: https://github.com/ushahidi/uchaguzi/commit/63ad22dbb4564bfbe8bcc85366019b72252d8878
