### ISSUE TITLE
Map View and List View UI missing - Reports

### ISSUE THREAD

**Issue by srutto** [ushahidi/uchaguzi#25]
This is on the Reports Page. Map view and List view are missing on the deployment.

Normal Ushahidi deployment: http://i.imgur.com/N3HcOJY.png
Uchaguzi deployment: http://i.imgur.com/mb1BiPw.png

**Comment by kamaulynder** [comment]
Closing this as for this particular deployment, we opted for a list view on report listing seeing there is another level of filtering on the main map (counties/constituencies)
