### ISSUE TITLE
Filter by Report/Media Type failure

### ISSUE THREAD

**Issue by aoduor** [ushahidi/uchaguzi#27]
Clicking on any of the options(Web, Email, Twitter, SMS for report type OR photos, video, news links ) yields no behaviour. Links seem to be inactive

**Comment by heatherleson** [comment]
Can we add audio as a format option too?

**Comment by aoduor** [comment]
The same issue described above applies for filtering by custom fields and by verification status

**Comment by rjmackay** [comment]
From my testing it seems the links work, but there is no styling to show what is active/not active. Still a major issue however

**Comment by kamaulynder** [comment]
Fixed
