### ISSUE TITLE
Tools navigation disappears 

### ISSUE THREAD

**Issue by srutto** [ushahidi/uchaguzi#35]
When you select the following tabs, the tools navigation disappears:
• Stats
• Manage
• Addons
• Users
• Reports/Create report
• Reports/Comments
• Reports/Download Reports
• Reports/Upload Reports
You have to keep going back to the "Tools" menu to get the navigation tabs.
![Screen Shot 2013-01-24 at 3 28 55 PM](https://f.cloud.github.com/assets/1751822/93409/d2c454a8-6621-11e2-960c-b58b13862998.png)

**Comment by eyedol** [comment]
This should be fixed from a recent commit I made. @srutto  mind testing again, so we can close this issue?

**Comment by srutto** [comment]
@eyedol Tested. All fixed so I'll go ahead and close this.
