### ISSUE TITLE
"Forgot Password" link missing in UI on login page

### ISSUE THREAD

**Issue by srutto** [ushahidi/uchaguzi#37]
![Screen Shot 2013-01-24 at 3 56 14 PM](https://f.cloud.github.com/assets/1751822/93473/92c917cc-6625-11e2-8b37-7e8a3e8ebd28.png)

**Comment by kamaulynder** [comment]
This requires an upgrade to 2.6.1 - fix is there

**Comment by rjmackay** [comment]
Fixed with https://github.com/ushahidi/uchaguzi/pull/54
