### ISSUE TITLE
Log out option does not exist

### ISSUE THREAD

**Issue by aoduor** [ushahidi/uchaguzi#4]
Steps to reproduce:-
- Log into uchaguzi admin dashboard
- Click on login/notifications on top right corner of page

Expected result
- Drop down with the option of logging out

Actual result
- Nothing happens: No dropdown appears. 

The option to log out does not exist anywhere else on the admin dashboard, meaning, once I log in, I can't log out :(

**Comment by kamaulynder** [comment]
Fixed
![Screen Shot 2013-01-16 at 12 38 22 PM](https://f.cloud.github.com/assets/155218/70761/9b741572-5fc0-11e2-9d33-b10e43a66984.png)
