### ISSUE TITLE
"Browse Files" on Gallery not working

### ISSUE THREAD

**Issue by srutto** [ushahidi/uchaguzi#41]
Go to Gallery
Go to Browse Files section on the right
Select All Reports 

Expected Result:
Show all reports

Actual Result:
Reloads the gallery page

The same happens for Popular Reports, Amplified Reports, Recent Reports and Flagged Reports

**Comment by eyedol** [comment]
@kamaulynder  Do we still want to implement this feature? Is the `Popular Reports`, `Amplified Reports`, `Recent Reports` and Flagged Reports` feature implemented? If it's then I can pull media based on those filters.

@srutto, actually when you click on `All Reports` it suppose to show all the media attached to all published reports.

**Comment by kamaulynder** [comment]
Axing this feature - filtering is done on the report listing page.
