### ISSUE TITLE
Language menu bar missing from uchaguzi website

### ISSUE THREAD

**Issue by aoduor** [ushahidi/uchaguzi#44]
The menu bar allowing users to switch languages when viewing the deployment is missing, site-wide.

![screenshot](http://i.imgur.com/q5qrd4t.png)

**Comment by kamaulynder** [comment]
@Jepchumba @brandonrosage , any idea on where we could place this on the main page/header??

**Comment by brandonrosage** [comment]
I'd propose implementing it in the users' dropdown menu. [It's semi-implemented now](https://github.com/ushahidi/uchaguzi/blob/master/application/views/header_nav.php#L15), commented out because it throws an application error
