### ISSUE TITLE
Site message and Site copyright statement don't show up on main page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/uchaguzi#49]
Site message and Site copyright statements are added on settings page.

Expected behaviour - they should both show up on the main page for visitors to see
Actual behaviour - they are not surfaced at all.

Same issue applies to site banner(though I'm assuming this is unnecessary for uchaguzi, but worth mentioning either way)

**Comment by kamaulynder** [comment]
mmh, maybe look into having a footer pinging @Jepchumba and @brandonrosage for this.

**Comment by brandonrosage** [comment]
The frontend prototype doesn't include a traditional footer. So unless @Jepchumba has one (or can provide one), this will need to be a new to-do or creating from scratch. 

Jep?

**Comment by brandonrosage** [comment]
I completed a simple implementation of this in today's commit: https://github.com/ushahidi/uchaguzi/commit/a0054602f5ae1bd9fd37769219a7a3d12eee6211
