### ISSUE TITLE
Browser compatibility issues

### ISSUE THREAD

**Issue by aoduor** [ushahidi/uchaguzi#5]
Category filter on the homepage appears fine on Firefox. See below
![screenshot](http://i.imgur.com/3re2t.png)
Doesn't work on chrome and Safari. See below
![screenshot-1](http://i.imgur.com/z3R3w.jpg)

**Comment by kamaulynder** [comment]
Fixed, now appears on chrome and firefox
![Screen Shot 2013-01-16 at 12 41 27 PM](https://f.cloud.github.com/assets/155218/70769/0634b042-5fc1-11e2-9d51-8934c689a28c.png)
