### ISSUE TITLE
Actionable plugin throws an error on install

### ISSUE THREAD

**Issue by kamaulynder** [ushahidi/uchaguzi#51]
1. Make sure plugin is installed
2. Click messages tab, from one of the messages click create report
3. This is shown -> http://grab.by/jMnA

Expected results
Two buttons, one actionable and another action taken are supposed to be displayed.

**Comment by rjmackay** [comment]
This happens when the plugin directory is not named `actionable`
ie. you ran git clone and it created a directory called `Ushahidi-plugin-actionable`

Just tested with the correct directory name and this works.

Closing - reopen if you think this is still an issue
