### ISSUE TITLE
Member UI - skewed

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/uchaguzi#57]
When a member or superadmin logs into the dashboard, their view is skewed. I was advised that a ticket or action was assigned. Adding as it is not in github

screenshot http://cl.ly/image/4133172Q1u2Y

**Comment by rjmackay** [comment]
Probably related or duplicate of #36

**Comment by kamaulynder** [comment]
Yes, working on it also.

**Comment by aoduor** [comment]
Closing, as is a duplicate of #36
