### ISSUE TITLE
CSS missing from /members/dashboard

### ISSUE THREAD

**Issue by jetherton** [ushahidi/uchaguzi#60]
Take a look at this screen shot. Chromium/Ubuntu 12.04
![Uchaguzi dash](https://f.cloud.github.com/assets/275566/162565/6af43fae-77c0-11e2-8588-10b1264882b0.png)

**Comment by rjmackay** [comment]
Related to/duplicate of #36 and #46 ?

**Comment by aoduor** [comment]
Closing, as is a duplicate of #36
