### ISSUE TITLE
Category - Minimize/Maximum

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/uchaguzi#61]
Sub-categories do not recollapse after clicking main category to view.

Expected process:
1. Click on main category to see sub-categories
2. Click on main category to recollapse the sub-categories.

This would make viewing categories on large deployments better. I tested on lern.ushahidi.com and https://www.takebackthetech.net/mapit//  This appears to be a longer term ushahidi ux thing to fix. 

Note: If I click on "urgent', it collapses all the previous categories. This is the only category that functions like this.

**Comment by kamaulynder** [comment]
Will not be handled for now.
