### ISSUE TITLE
Election plugin breaks Admin User editing

### ISSUE THREAD

**Issue by aoduor** [ushahidi/uchaguzi#63]
Throws a database error shown below:-

![screenshot](http://i.imgur.com/gmwrsQ7.png)

**Comment by heatherleson** [comment]
tried to upgrade role /member of a person in ushahididev and got this error:
An error was detected which prevented the loading of this page. If this problem persists, please contact the website administrator.

plugins/election/hooks/election.php [174]:

Undefined index: adminsection_title

Report This Issue To Ushahidi
