### ISSUE TITLE
About and Info pages

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/uchaguzi#66]
The Info Pages are not effective in explaining what the deployment is, how to report and how to get involved. 
1. what is the deployment "about page" needs more content in a nicer format
   a. what is the deployment
   b. logos
   c. who is the uchaguzi audience (see audience wiki pages)
2. how to add reports
   a. how to add reports by all the formats
   b. explain what happens to the reports
3. FAQ
   a. provide a clear FAQ on how to use uchaguzi, how to get involved and etc. 
   b. link to wiki on how to get involved and how we will work 

Put the elections and how to vote details all under one tab. While the goal is to help with the election monitoring and education is important, it is not the goal of the deployment.

Heather offers to do a first draft on this. Editors and CSS will be needed

**Comment by rrbaker** [comment]
(per Juliana's request)
1. Partners (may need some styling love to get the partner logos included)

**Comment by rrbaker** [comment]
@heatherleson: Do you see this pages are repurposing content from the wiki? Linking to the wiki? Combination of both?

**Comment by heatherleson** [comment]
Info page breakdowns:
1. Partners page = see above. 
2. Audience and users pages - FAQ and How to Report
   a. FAQ - basic 101 who, what happens with your reprots, where, why uchaguzi  (10 or less then point to a wiki article)
   b. how to report - shiny - how to sms, how to email, formats, taxonomy of SMS, 5 steps to a great online web report etc. Push the reset to the wiki
   c how to get involved. push them to a wiki link. could just be one of the top 10 FAQs

**Comment by heatherleson** [comment]
Draft FAQ to be added to platform - https://wiki.ushahidi.com/display/WIKI/Uchaguzi+FAQ
(Moving it to basecamp)

**Comment by kamaulynder** [comment]
Css issues and layout fixed, if anything the rest of the conversation on docs should move to basecamp, closing this.
