### ISSUE TITLE
Runtime error - Reset Password

### ISSUE THREAD

**Issue by srutto** [ushahidi/uchaguzi#67]
Tested on http://uchaguzi.ushahididev.com/
Steps to Reproduce:
1. Click on "forgot password" link
2. Enter registered email address
3. Reset password
4. Receive reset password link in registered email address
5. Follow link

Expected result:
Redirect to page to change password

Actual result:
Runtime error: Undefined variable: changeid
![Screen Shot 2013-02-18 at 11 22 29 PM](https://f.cloud.github.com/assets/1751822/168799/961d993c-7a09-11e2-8218-1e94aadb442d.png)

**Comment by rjmackay** [comment]
Assigning this to me - probably broken by the security fixes. I tested this locally but must have broken during the merge.
