### ISSUE TITLE
Get alerts slider not marked

### ISSUE THREAD

**Issue by jetherton** [ushahidi/uchaguzi#68]
The slider that lets you set the radius for alerts isn't marked. There's nothing to indicate what it does. Also, when I change my radius to 100 km the text at the top of the map, "Or place a spot on the map below, and we will alert you when a report is submitted within 20 kilometers." didn't update to say 100 kilometers instead of 20.  See image. I'm running chromium on ubuntu 12.04
![Uchaguzi get alert](https://f.cloud.github.com/assets/275566/172415/1a3c123c-7abb-11e2-9fd0-55848e502811.png)

And finally, this is minor, the color of the map and the background color of the site are very similar and kind of blend together. I realize this is a personal preference, but if it were up to me I'd add a border around the map.

**Comment by srutto** [comment]
@jetherton this issue has already been reported #34. Mind adding the additional ones you've mentioned in there? Closing this out as it's a duplicate.

**Comment by jetherton** [comment]
Sure, I can copy and paste things.

John Etherton
Managing Partner
Etherton Technologies, Ltd.
+1-404-578-1606
john@ethertontech.com mailto:john@ethertontech.com
