### ISSUE TITLE
Typing in lat, lon throws error when typing negative numbers, empty strings, and ints with trailing decimal.

### ISSUE THREAD

**Issue by jetherton** [ushahidi/uchaguzi#69]
On the /admin/reports/edit page, when you type in a negative number like -3 for lat or lon, you get an error that "-" is not a valid number. See attached image. 

Also, if you clear out one of the fields, so you can type in a new number, you get "NaN" in both fields. 

Finally if you type in "34" and then try to type a decimal to specify 34.4, the JS removes the "." because "34." and "34" are the same thing to it.

The JS needs to be able to accept partially typed in numbers and not over react. 
![invalid number](https://f.cloud.github.com/assets/275566/172444/f4859026-7abb-11e2-8fcf-f80e79840849.png)

**Comment by kamaulynder** [comment]
Fixed
