### ISSUE TITLE
Clean URLs option inconsistent with options selected

### ISSUE THREAD

**Issue by aoduor** [ushahidi/uchaguzi#7]
Despite the fact that this is automatically set to NO, sometimes, my URLs are clean, sometimes they're not.
e.g for homepage - [my_url]/index.php/main
Addons page - [my_url]/admin/addons/plugins/

**Comment by kamaulynder** [comment]
Closing this as I can't reproduce on my local or the live site http://simulation.uchaguzi.co.ke/
