### ISSUE TITLE
User Sign Up - Password Validation

### ISSUE THREAD

**Issue by ghost** [ushahidi/uchaguzi#70]
• auth.password.alpha_numeric

I got this as an error/remark when I chose my own password.
Probably it didn't meet the validation criteria and was rejected because my account sign up didn't go through.

Ideal behaviour should be a remark/help message saying what kind of password the user should come up with.

**Comment by srutto** [comment]
Steps to reproduce:
1.Create account
2.Enter password that has has no alphanumeric characters, eg:  /'.,|=

Expected Result:
Notification message saying the password should have alphanumeric characters

Actual Result
![Screen Shot 2013-02-27 at 1 31 50 PM](https://f.cloud.github.com/assets/1751822/200481/f0ade864-80c8-11e2-83a2-a02a4876c53f.png)
