### ISSUE TITLE
Too many alerts sent

### ISSUE THREAD

**Issue by jetherton** [ushahidi/uchaguzi#71]
I signed up for alerts and received 5 alerts when I approved a report that fell within my specified radius and category constraints.  I expected to only receive one alert.

All the emails were dated at the same time and were for report http://uchaguzi.ushahididev.com/reports/view/93

**Comment by srutto** [comment]
Confirmed. I got 2 alerts after approving a report that fell within the category I subscribed for. @kamaulynder ping.
