### ISSUE TITLE
Emergency number disclaimer

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/uchaguzi#76]
Not sure if this makes sense for uchaguzi (please inform from past deployments) but should we add the standard 911 warning message? ie.
'PLEASE READ: This reporting system is NOT a replacement for 9-1-1. If you are experiencing an emergency or need to officially report an incident, please call 9-1-1 or the public safety non-emergency number at ***. This reporting system is for XYZ'

**Comment by kamaulynder** [comment]
Nice suggestion, having Daudi and Kipp structure the message in a Kenyan context then we put it up. Thanks for this.

**Comment by aoduor** [comment]
Looks like this has been done, on the footer.

![screenshot](http://i.imgur.com/DvTUHFP.png)
