### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by aoduor** [ushahidi/uchaguzi#77]
Passwords get reset successfully, but this message is what the user gets after successully resetting.

![screenshot](http://i.imgur.com/rm69Dio.png)

**Comment by rjmackay** [comment]
What url did you end up at when you got that? Does this happen for multiple users?
Were their special characters in the password you reset to? or the username?
I just managed to reset my password with no issues

**Comment by aoduor** [comment]
Here's the URL https://uchaguzi.co.ke/login?change_pw_success?change_pw_success&change_pw_success
 I tried with two of my accounts and had the same issue. Debra also had the same issue. There were no special characters in my password, and even though i got that funny message, I managed to log in with the new password I set

**Comment by rjmackay** [comment]
Ah ok.. looks like this happens on the live site but not uchaguzi.ushahididev.com
Might be a bug with the server set up, or kohana getting confused by nginx.. need to test more before I'm sure.
The error comes from somewhere buried in Kohana's input filtering..

**Comment by rjmackay** [comment]
I've made some fixed to the redirect rules on the server - can you retest and let me know what happens?

**Comment by srutto** [comment]
Retested this. You get a notification saying the password has been changed successfully. I'll go ahead and close this.
![Screen Shot 2013-02-26 at 10 59 44 PM](https://f.cloud.github.com/assets/1751822/198096/2e571d18-804f-11e2-82cf-d50f6f2a01e4.png)
