### ISSUE TITLE
User login screen skewed

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/uchaguzi#82]
1. goto uchaguzi.co.ke on ff
2. view screen "login" button on top right hand side.
3. I see a weird number

![5v](https://f.cloud.github.com/assets/1216707/187962/9daf96c8-7dab-11e2-99b1-55e68362af9b.png)
4. Click on reports
5. See that I have to login

Proceed

**Comment by kamaulynder** [comment]
Duplicate of #80, closing this.
