### ISSUE TITLE
Report "approved" but no edit log

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/uchaguzi#83]
Report #48 is listed as "approved" but there is no edit log. This is urgent. 
1. view reports approved page
2. see report #48 (this report has now been "unapproved" due to wrong type of report.
3. The green button lists as "approved"

I deselected approved. This report needs to be deleted from the system 
![5w](https://f.cloud.github.com/assets/1216707/187974/af0588ea-7dad-11e2-97c7-78ded1557bd4.png)

another example
![5y](https://f.cloud.github.com/assets/1216707/187985/5c8f7a68-7db1-11e2-9aef-f86b40127a36.png)

**Comment by rjmackay** [comment]
Probably worth adding the revisioning or track changes plugins to get better edit logs.
The current behaviour is still a bug however

**Comment by rjmackay** [comment]
Added #85 to track the plugin suggestion

**Comment by rjmackay** [comment]
I haven't been able produce a similar report with this issue. I'm wondering if its this was possibly left over from an early CSV import?

There are a few reports like this in the system. ie report 48:
http://uchaguzi.co.ke/reports/view/48
http://simulation.uchaguzi.co.ke/reports/view/48

**Comment by heatherleson** [comment]
I tested on the dev site and edits appeared. I think this really needs more rigorous testing than me looking at 4 reports as a superadmin. Perhaps someone could test csv reports upload again

**Comment by kamaulynder** [comment]
Cleaning the reports table, so much clutter.

**Comment by kamaulynder** [comment]
Closing this, reports are on the 0 mark, no imports
