### ISSUE TITLE
Location search returns results, "(0 results)"

### ISSUE THREAD

**Issue by rrbaker** [ushahidi/uchaguzi#87]
Searching reports by location yields some reports but reads "(0 reports)" in the listing.

OS X 10.8/Firefox 19

**Comment by srutto** [comment]
@rrbaker can't seem to reproduce this. Searching by location on http://uchaguzi.ushahididev.com/ returns the number of reports in the listing. 
![Screen Shot 2013-02-28 at 11 59 29 AM](https://f.cloud.github.com/assets/1751822/204679/7e6b2128-8185-11e2-9805-444279dda67d.png)

Closing this for now.
