### ISSUE TITLE
SMS messages /trusted reporters workflow

### ISSUE THREAD

**Issue by heatherleson** [ushahidi/uchaguzi#93]
SMS reports from partners are to appear in the "Trusted Reporters" field in Green. The SMS reports in the "All messages" fields also all appear in green text. This is so confusing. Also, who are the "trusted reporters" in blue? 

Suggestion:  make the "all messages" a different colour than blue or green. This has to be very very clear for all of us to process mass amounts of reports.

These were the docs provided about why reports are "green":
https://wiki.ushahidi.com/display/WIKI/Uchaguzi+SMS+Step+by+Step

Screenshots from uchaguzi.co.ke as the reports are not on the dev site to test.

The all "messages" screen:
![5z](https://f.cloud.github.com/assets/1216707/190437/c43b7030-7eed-11e2-8abc-531c43b9714a.png)

The "trusted reporters" screen:
![5-](https://f.cloud.github.com/assets/1216707/190438/caedc964-7eed-11e2-96e4-06237297253a.png)

**Comment by kamaulynder** [comment]
This was clarified on a call, closing this.
