### ISSUE TITLE
Create a "To be geolocated" tab on admin reports listing page

### ISSUE THREAD

**Issue by aoduor** [ushahidi/uchaguzi#95]
Have a tab that filters out reports that have not been geolocated yet, a la "awaiting approval/verification" tabs.

This will go a long way in helping the geolocation team identify reports that require translation, as opposed to having them search/manually scroll through the entire reports listing page for this.. 

pinging the awesome @kamaulynder

**Comment by rjmackay** [comment]
I think we often used a hidden category for this, so reports were manually assigned to that queue.. if we're following that model I could backport the admin reports search from core to help with filtering.
@heatherleson how have SBTF typically done this?

**Comment by heatherleson** [comment]
Yes, we use hidden categories and people search by those

**Comment by kamaulynder** [comment]
Yep, thats what we have and this tab is just to separate the teams, will handle
